### ISSUE TITLE
Mobile frontend für Webserver

### ISSUE THREAD

**Issue by top-on** [ThorbenJensen/green-wave#5]
Web-App für Eingabe durch Nutzer:
- [ ] Welche Phase hat jetzt gerade begonnen
- [ ] Wie viele Sekunden (schätzt Nutzer) wird diese Phase Dauern
- [ ] OPTIONAL: Letzte Eingabe rückgängig machbar machen
Ausgabe im in Web-App:
- [ ] Anzeigen wie lange aktuelle Phase noch dauern wird (laut Schätzung Backend), in Sekunden

**Comment by silberzwiebel** [comment]
Brauchen wir doch nicht.
